### ISSUE TITLE
Migration from Jekyll to Cecil

### ISSUE THREAD

**Issue by sooluh** [smkn1pml/try-cecil#1]
### Tasks

- [x] Addopting data from old website
- [ ] Applying website template

### Features

- [ ] Landing page
    - [ ] Hero section
    - [ ] Summary section
    - [ ] Vision, missions, goals section
    - [ ] Major lists section
    - [ ] Extracurricular lists section
    - [ ] Alumni testimonial section
    - [ ] Latest article section
- [ ] Article lists
- [ ] Article detail
- [ ] Major detail
- [ ] History page
- [ ] Vision & mission details
- [ ] Facilities page
- [ ] Profile page
- [ ] Admissions page
- [ ] Graduate page
    - [ ] Filling out testimonials
- [ ] Contact page
    - [ ] Working contact form
